### ISSUE TITLE
Custom variables

### ISSUE THREAD

**Issue by mariteaux** [dotcomboom/AutoSite#1]
Running into a very specific problem with AutoSite. I name the files for my music reviews very consistently, with a long-hand title as the display and a shorthand title everywhere else (so the HTML for Earlimart's *Everyone Down Here* is named `everyonedownhere.html` and the cover is named `everyonedownhere.jpg`). Simple enough.

Issue being, for Open Graph stuff, there's no way to have the script plug in that shorthand, since there's nowhere for it to go. Unless I were to have the entirety of the `<head>` inside each individual page (which defeats the point), I can't have the album art popping up with the Open Graph embed.

Any way to implement custom variables so I can have my album art?

**Comment by dotcomboom** [comment]
Implemented with the new attribute system: https://github.com/dotcomboom/AutoSite/commit/f7a5e491abfd102a77dfb196a2e5fcd9af757e9a
