### ISSUE TITLE
<=XP Compatibility broke

### ISSUE THREAD

**Issue by dotcomboom** [dotcomboom/AutoSite#36]
Shell32 references (used for extracting zips) break compatibility.

**Comment by nithilan4** [comment]
oh no

**Comment by dotcomboom** [comment]
![](https://cdn.discordapp.com/emojis/677334652440018955.png?v=1) ![](https://cdn.discordapp.com/emojis/677334676569980939.png?v=1)

**Comment by dotcomboom** [comment]
Forgot to close this earlier.
